### ISSUE TITLE
wg-stories Meeting April 2020

### ISSUE THREAD

**Issue by newmuis** [ampproject/wg-stories#36]
**Meeting date/time (UTC)**

2020-04-29 from 5:00 to 6:00pm GMT

**Instructions for joining the meeting**

https://meet.google.com/jvw-ssvf-bvu

**Agenda**

https://app.sli.do/event/9xreh2ak

**Comment by Enriqe** [comment]
# Stories WG April 2020 Meeting Notes

_(Stories core team initials are in **bold** to help distinguish)_

(PG) Page attachments: Can we get rid of the page attachments remote URL feature until we get a similar experience to instagram/facebook? Current behavior is confusing.

**(GM)** We have done a lot of exploration in this space. Main concern is that the web behaves differently than a native app. There are cases where the embedded site can block cross-origin requests, and the containing page has no way of knowing this, causing errors and an unpredictable user experience. 

(PG) Shouldn’t this be treated as a developer experience problem, not a user problem?

**(GM)** The developer can preview the story before they publish it, but that doesn’t guarantee that it will continue to work in the future.

(PG) Concerns about bounce rates increasing because of this. Also not knowing how to get back to the story after going into the swipe up. If it’s that difficult, we should drop the URL feature. Concerns about a consistent experience between inline and remote URLs.

**(GM)** Agreed that the inconsistent UX between inline and remote URLs. But we think that even if it’s not good on the web, it can be good in a native app (CCT / webview), this is enough to keep it.

(CA) Is there a reason why it doesn't open in a new tab?

**(GM)** Biggest reason is that it’s not possible in Safari. Safari doesn’t interpret it as a “trusted gesture”. It requires it to be a click and not a swipe.

(CA) It feels good, has some quirks (because of early stages) (e..g doesn't play in the player/safari). _(Editor's note: working on this, please see https://github.com/ampproject/amphtml/issues/27944)_

(PG) Can we whitelist the iframe so that we can implement the feature for our customers? 

**(JN)** It’s hard to guarantee that experience, and to bring consistency across stories. We are also worried about scrollable content inside the iframe, which could potentially break the affordance of closing the drawer. What are the main features that customers would like to have?

(PG) Main one is forms inside page attachments. We will ask and get back.
(CA) +1 on the forms. It would be quite nice to have in the inline page attachments. And solve quite a few issues. Or having any kind of input inside the page attachment.

**(VR)** What kind of forms? Polls, registration?

(CA) Mostly capturing information / lead capture

(CA) What are the updates on the quizzes and polls?

**(JN)** We started a couple of initiatives there. One is a round around the implementation of the poll. We’ve had the quiz component largely complete, but doing the due diligence to not cause churn for creators. We believe these will be very similar. We’ll be launching them as a suite of components which ideally are very easy to switch around. Also will probably share the same backend and APIs. We just want to make sure we consider everything so that we don’t make any breaking changes. We are abstracting logic and prototyping the look and feel of these components.

What kind of content would you like to have in the quizzes / polls?

(PG) Some [customers] are producing polls, a lot of CTAs, information stories (e.g. we have a customer producing 20 stories in cockroaches). Inline forms. Customers want the Y/N button from instagram. They want to know how many people are choosing certain option in a two-choice poll. Branching was one of them. There are the 3 main requested (forms, Y/N polls, branching).

(CA) Here at tappable we haven’t had many thoughts on this. Which Harry potter house you belong to would be cool, and getting the scores of answers.

(PG) I see STAMP as a framework that you can extend. We are thinking of extending our own functionalities.

**(JN)** Main concerns here are distribution which can cause some more problems in the long run.

(CP) I would also like to add that an experience where a certain choice in a quiz / poll takes you to a certain page. This would yield great story-telling experiences.

(PG) Since this industry is evolving really quickly we want to urge in moving quicker regarding these features.

**(JN)** Would having forms inline be expedited and fulfill your needs? Also wanted to clarify in the distribution (UNDP). The UN story that was featured in Google’s Discover app. Google and other platforms have taken the stance that validation is important for this reason. For user security and privacy. So those platforms won’t show the stories if they are not valid. So there are drawbacks here on branching out of the framework.

(PG) Users we are getting are using AMP stories for several use cases (e.g. intranets). They don’t really care if they get distributed in google.

(AB) How to integrate amp stories in the future. Some people are integrating our stories in their websites. Are there any plans of integrations with big platforms in the future like Facebook / LinkedIn natively?

**(JN)** That is largely not our decision. It mostly lies in Facebook / Linkedin. From an architectural perspective, the amp-story-player would be ideal for this. If I were a privacy / security engineer at e.g. Linkedin. I would think it would be wise to load the stories from a reputable location. In this case the cache origin follows a reputable security validation.

The idea of making it easy for other platforms to integrate is an important point. 

(ES) On the subject of Makestories using amp-stories as a framework, isn't there also a problem about maintaining stories? I would assume that google cannot ensure your stories will still work after updates if the stories are not AMP-compliant ?

**(JN)** This is absolutely true. The AMP validator is the contract between the framework and framework-users. If things don’t validate, there are a number of things that could be broken. We make a lot of assumptions of how the document is structured, etc.. It would be very easy for users to break things accidentally, so the validator serves as rail guards for this.

* Demo of using polls (Codepen) [link](https://codepen.io/mszylkowski/full/KKdzvPQ) 

(PG) Cool! When is this launching?

**(JN)** There’s still a bit of plumbing we have to figure out, making sure the backend APIs are stable. We’ll have a better estimate in the next working group meeting.

(PG) & (CA) We’d like to show the data on answers for our story creators. Not have them depend on having to go to Google to see the results. Having control of the backend would also be cool.

(CA) Being able to self-hosting the library would also be cool

**(VR)** How are analytics working for folks?

(CA) Can you get in touch with me, we’re doing some interesting things there. _(Editor’s note: please feel free to use the #wg-stories channel on AMP's Slack ([signup](https://docs.google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform?fbzx=4406980310789882877)) to get in touch with the team!)_

(PG) Any updates on the player? When is the API going to be available?

(EM) Apologies for the delay on this, I’ll be picking up work on it this week. This should be available soon and ready to use by the next WG meeting. Here is a [tracking issue](https://github.com/ampproject/amphtml/issues/27331) that you can follow and discuss if you’re interested. Also FYI we have launched an API to load stories inside the player from the cache to improve loading performance, read more [here](https://github.com/ampproject/amphtml/issues/27588).

**Comment by newmuis** [comment]
Thanks again @Enriqe for taking such detailed notes!
